CREATE TABLE TB_SEDE(
	PK_ID_SEDE SERIAL PRIMARY KEY,
	VAR_PAIS VARCHAR(255) NOT NULL,
	VAR_UF VARCHAR(255) NOT NULL,
	VAR_CIDADE VARCHAR(255),
	VAR_LOGRADOURO VARCHAR(255),
	INT_NUMERO INTEGER,
	INT_CEP INTEGER,
	VAR_COMPLEMENTO VARCHAR(255)
);