CREATE TABLE TB_INSTITUICAO(
	PK_ID_INSTITUICAO SERIAL PRIMARY KEY,
	VAR_TIPO_INSTITUICAO VARCHAR(255) NOT NULL,
	VAR_FUNDADOR VARCHAR(255) NOT NULL,
	DATE_FUNDACAO DATE NOT NULL,
	VAR_PRESIDENTE VARCHAR(255),
	VAR_REPRESENTANTE VARCHAR(255),
	VAR_DIRETOR VARCHAR(255)
);